# les fichier .yml sont des fichier de configuration tel que xml 

name: Push Event Workflow

on: push                           # s'active lorsque l'on push sur la main

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Python unit tests et pytest 
      run: python3 -m unittest test_calcul_unittest.py  #l'action qu'il execute sur la main a chaque push

    - name: Run Pytest
      run: |
        pytest
      
