name: Run Pytest on push

on: push  # ajustez la branche selon votre configuration

jobs:
  test:
    runs-on: ubuntu-latest  # Choisissez l'image selon vos besoins
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ajustez cela en fonction de votre configuration

    - name: Run Pytest
      run: |
        pytest
